name: Python CICD Kata
run-name: Pyhton CICD Kata
on: [push]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Set up python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: uv run ruff format .